"""Accès PostgreSQL (psycopg 3) : connexion par requête, transactions explicites.

L'API reste celle de l'ancienne version SQLite (query / scalar / execute / transaction) :
le reste du code n'a presque pas changé. Les requêtes gardent les « ? » : ils sont convertis en « %s ».
"""
import re
from contextlib import contextmanager

import psycopg
from flask import current_app, g
from psycopg.adapt import Loader
from psycopg.types.numeric import IntDumper

SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    is_admin INTEGER NOT NULL DEFAULT 0,
    is_active INTEGER NOT NULL DEFAULT 1,
    must_change_password INTEGER NOT NULL DEFAULT 0,
    session_version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    description TEXT,
    image_url TEXT,
    position INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    author TEXT NOT NULL,
    author_slug TEXT NOT NULL,
    publisher TEXT,
    isbn TEXT,
    language TEXT NOT NULL DEFAULT 'Français',
    pages INTEGER,
    format TEXT,
    year INTEGER,
    description TEXT NOT NULL DEFAULT '',
    highlights TEXT NOT NULL DEFAULT '',
    price INTEGER NOT NULL,
    old_price INTEGER,
    cost_price INTEGER NOT NULL DEFAULT 0,
    stock INTEGER NOT NULL DEFAULT 0,
    low_stock_threshold INTEGER NOT NULL DEFAULT 5,
    cover_url TEXT,
    category_id INTEGER REFERENCES categories(id) ON DELETE SET NULL,
    badge TEXT NOT NULL DEFAULT '',
    is_featured INTEGER NOT NULL DEFAULT 0,
    is_published INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS ix_books_category ON books(category_id);
CREATE INDEX IF NOT EXISTS ix_books_author ON books(author_slug);
CREATE INDEX IF NOT EXISTS ix_books_created ON books(created_at);

CREATE TABLE IF NOT EXISTS book_images (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    url TEXT NOT NULL,
    caption TEXT,
    position INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_book_images_book ON book_images(book_id);

CREATE TABLE IF NOT EXISTS reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    author_name TEXT NOT NULL,
    city TEXT,
    rating INTEGER NOT NULL,
    comment TEXT NOT NULL,
    is_visible INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS ix_reviews_book ON reviews(book_id);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    tracking_code TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    wilaya_code INTEGER NOT NULL,
    wilaya_name TEXT NOT NULL,
    commune TEXT NOT NULL,
    address TEXT,
    delivery_method TEXT NOT NULL DEFAULT 'home',
    delivery_price INTEGER NOT NULL DEFAULT 0,
    subtotal INTEGER NOT NULL DEFAULT 0,
    total_amount INTEGER NOT NULL DEFAULT 0,
    payment_method TEXT NOT NULL DEFAULT 'cash_on_delivery',
    status TEXT NOT NULL DEFAULT 'pending',
    is_notified INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS ix_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS ix_orders_created ON orders(created_at);
CREATE INDEX IF NOT EXISTS ix_orders_user ON orders(user_id);

CREATE TABLE IF NOT EXISTS order_items (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE RESTRICT,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price INTEGER NOT NULL,
    cost_price INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS ix_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS ix_order_items_book ON order_items(book_id);

CREATE TABLE IF NOT EXISTS stock_movements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id INTEGER NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    admin_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    change INTEGER NOT NULL,
    reason TEXT NOT NULL DEFAULT '',
    stock_after INTEGER NOT NULL,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))
);
CREATE INDEX IF NOT EXISTS ix_stock_book ON stock_movements(book_id, created_at);

CREATE TABLE IF NOT EXISTS subscribers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT (to_char(timezone('utc', now()), 'YYYY-MM-DD HH24:MI:SS'))
);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS throttle (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket TEXT NOT NULL,
    ident TEXT NOT NULL,
    created_at DOUBLE PRECISION NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_throttle ON throttle(bucket, ident, created_at);
"""


# ───────────────────────── Types : comportement identique à l'ancienne version SQLite ─────────────────────────
class _NumericLoader(Loader):
    """NUMERIC (AVG, ROUND…) -> int ou float, jamais Decimal (sinon les pages afficheraient 4.5000000)."""
    def load(self, data):
        text = bytes(data).decode()
        return float(text) if "." in text else int(text)


class _BoolAsInt(IntDumper):
    """Les colonnes 0/1 sont des INTEGER : on envoie True/False comme 1/0."""
    def dump(self, obj):
        return super().dump(int(obj))


psycopg.adapters.register_loader("numeric", _NumericLoader)
psycopg.adapters.register_dumper(bool, _BoolAsInt)


class Row:
    """Ligne de résultat : row["col"], row[0], row.keys(), dict(row) — comme sqlite3.Row."""
    __slots__ = ("_names", "_values")

    def __init__(self, names, values):
        self._names, self._values = names, values

    def __getitem__(self, key):
        if isinstance(key, (int, slice)):
            return self._values[key]
        try:
            return self._values[self._names.index(key)]
        except ValueError:
            raise KeyError(key) from None

    def keys(self):
        return list(self._names)

    def get(self, key, default=None):
        return self[key] if key in self._names else default

    def __iter__(self):
        return iter(self._values)

    def __len__(self):
        return len(self._values)

    def __contains__(self, key):
        return key in self._names

    def __repr__(self):
        return f"Row({dict(zip(self._names, self._values))})"


def _row_factory(cursor):
    names = [c.name for c in (cursor.description or [])]
    return lambda values: Row(names, values)


# ───────────────────────── Connexion ─────────────────────────
_INSERT = re.compile(r"^\s*INSERT\s+INTO\s+(\w+)", re.IGNORECASE)
_NO_ID_TABLES = {"settings"}  # tables sans colonne « id »


def _adapt(sql, args):
    """? -> %s, et on double les % littéraux. Retourne (sql, args, veut_lastrowid)."""
    if not args:
        return sql, None, False
    return sql.replace("%", "%%").replace("?", "%s"), tuple(args), True


class Cursor:
    def __init__(self, cur, lastrowid=None):
        self._cur, self.lastrowid = cur, lastrowid

    @property
    def rowcount(self):
        return self._cur.rowcount

    def fetchone(self):
        return self._cur.fetchone() if self._cur.description else None

    def fetchall(self):
        return self._cur.fetchall() if self._cur.description else []

    def close(self):
        self._cur.close()


class Connection:
    def __init__(self, raw):
        self.raw = raw

    def execute(self, sql, args=()):
        sql, params, _ = _adapt(sql, args)
        returning_id = False
        m = _INSERT.match(sql)
        if m and m.group(1).lower() not in _NO_ID_TABLES and "RETURNING" not in sql.upper():
            sql, returning_id = sql.rstrip().rstrip(";") + " RETURNING id", True
        cur = self.raw.cursor(row_factory=_row_factory)
        cur.execute(sql, params)
        last = None
        if returning_id:
            row = cur.fetchone()          # None si ON CONFLICT DO NOTHING n'a rien inséré
            last = row[0] if row else None
        return Cursor(cur, last)

    def close(self):
        self.raw.close()


def connect(dsn):
    raw = psycopg.connect(dsn, autocommit=True, connect_timeout=10)  # autocommit : transactions explicites
    return Connection(raw)


def get_db():
    if "db" not in g:
        g.db = connect(current_app.config["DATABASE"])
    return g.db


def close_db(_exc=None):
    conn = g.pop("db", None)
    if conn is not None:
        conn.close()


def init_db():
    conn = get_db()
    # Verrou : plusieurs workers gunicorn démarrent en même temps, un seul crée les tables à la fois.
    conn.execute("SELECT pg_advisory_lock(2800)")
    try:
        conn.execute(SCHEMA)
    finally:
        conn.execute("SELECT pg_advisory_unlock(2800)")


def query(sql, args=(), one=False):
    cur = get_db().execute(sql, args)
    rows = cur.fetchall()
    cur.close()
    if one:
        return rows[0] if rows else None
    return rows


def scalar(sql, args=(), default=0):
    row = query(sql, args, one=True)
    if row is None or row[0] is None:
        return default
    return row[0]


def execute(sql, args=()):
    cur = get_db().execute(sql, args)
    last = cur.lastrowid
    cur.close()
    return last


@contextmanager
def transaction():
    """BEGIN … COMMIT. Les mises à jour sensibles (stock) utilisent « WHERE stock >= ? » ou « FOR UPDATE »."""
    conn = get_db()
    conn.execute("BEGIN")
    try:
        yield conn
    except BaseException:
        conn.execute("ROLLBACK")
        raise
    else:
        conn.execute("COMMIT")


def get_setting_map(defaults):
    data = dict(defaults)
    for row in query("SELECT key, value FROM settings"):
        if row["key"] in data:
            data[row["key"]] = row["value"]
    return data


def set_setting(key, value):
    execute(
        "INSERT INTO settings(key, value) VALUES(?, ?) "
        "ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        (key, value),
    )
